blank_issues_enabled: true

contact_links:
  - name: MtF.wiki
    url: https://github.com/mtf-wiki/MtF-wiki/issues/new/choose
    about: MtF.wiki
  - name: 2345.LGBT
    url: https://github.com/mtf-wiki/2345.LGBT
    about: 跨性别导航 2345.LGBT
